title = "Tofan0810 Portfolio"
baseURL = "https://tofan0810.github.io/my-portfolio/"
theme = "hugo-resume"
canonifyURLs = true
uglyURLs = false
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

# --- ĐƯA CẤU HÌNH ĐỊNH DẠNG LÊN TRÊN ĐẦU TOÀN CỤC ---
[mediaTypes."text/vcard"]
suffixes = ["vcf"]

[outputFormats.vcard]
mediaType = "text/vcard"
baseName = "contact"
isPlainText = true
notAlternative = true

[outputs]
home = ["HTML", "JSON"]
page = ["HTML"]

[taxonomies]
tag = "tags"

# --- CÁC THÔNG SỐ CÁ NHÂN CỦA BẠN ---
[params]
address = "Ho Chi Minh City, Vietnam"
email = "tn421015@gmail.com"
favicon = "/favicon.ico"
firstName = "Nguyen Khanh"
lastName = "Toan"
phone = ""
profileImage = "/img/avatar.jpg"
showQr = true
showContact = true
showBoards  = false
showCertifications = false
showExperience = true
showProjects = true
showPublications = false
showEducation = true
showSocializations = true
showSkills = true
showBlog = false
sections = ["education", "projects", "experience", "skills"]
vcardfields = [
    "name",
    "image",
    "org",
    "email",
    "workemail",
    "phone",
    "url",
    "title"
]

[params.google]
[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/tofan0810/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/tofan0810"

[[params.handles]]
    name = "Facebook"
    link = "https://www.facebook.com/nguyen.toan.631296"

[[params.handles]]
    name = "YouTube"
    link = "https://www.youtube.com/@NguyenToan_dev"
    icon = "youtube"

